version: '3.8'

services:
  db:
    image: carlosquintanilha/dbimage:latest
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    ports:
      - "5432:5432"
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager # Opcional: útil se o volume dos dados do banco estiver preso a um nó específico

  api:
    image: carlosquintanilha/apiimage:latest
    environment:
      DB_HOST: db
      DB_PASSWORD_FILE: /run/secrets/db_password
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 2
    secrets: 
      - db_password

  frontend: 
    image: carlosquintanilha/frontendimage:latest
    environment:
      API_URL: http://nginx:80/api
      UPDATED: yes
    deploy:
      replicas: 3

  nginx: 
    image: carlosquintanilha/nginximage:latest
    ports: 
      - "80:80"
    deploy:
      replicas: 1
    
secrets:
  db_password:
    file: ./db/password.txt