version: '3.8'

services:
  prometheus:
    image: prom/prometheus:latest
    user: root 
    configs:
      - source: prometheus_config
        target: /etc/prometheus/prometheus.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    
    ports:
      - "9090:9090"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    privileged: true
    ports:
      - target: 8080
        published: 8080
        mode: host
    deploy:
      mode: global
      labels:
        prometheus_job: cadvisor
  node-exporter:
    image: prom/node-exporter:latest
    privileged: true
    deploy:
      mode: global
    
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_DISABLE_LOGIN_FORM=false
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_SECURITY_COOKIE_SECURE=false
      - GF_USERS_DEFAULT_THEME=dark
      - GF_SECURITY_ADMIN_EMAIL=admin@localhost
      - GF_SECURITY_DISABLE_INITIAL_ORG_SETUP=false
      - GF_FEATURE_TOGGLES_ENABLE=
      - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=false
      - GF_SECURITY_DISABLE_BRUTE_FORCE_LOGIN_PROTECTION=false
      - GF_SECURITY_FORCE_CHANGE_PASSWORD=false
    configs:
      - source: grafana_datasource
        target: /etc/grafana/provisioning/datasources/prometheus.yml
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

configs:
  prometheus_config:
    file: ./prometheus.yml
  grafana_datasource:
    file: ./grafana-datasource.yml
