apiVersion: v1
kind: Pod
metadata:
  name: dbpod
spec:
  containers:
  - name: db
    image: carlosquintanilha/dbimage
    ports:
    - containerPort: 5432
  env:
    - name: POSTGRES_PASSWORD
      value: "M@sterkey123"