apiVersion: v1
kind: Pod
metadata:
  name: apipod
spec:
  containers:
  - name: api
    image: carlosquintanilha/apiimage
    ports:
    - containerPort: 8000
    env:
    - name: DB_PASSWORD
      value: "M@sterkey123"
    - name: DB_HOST
      value: "db"