apiVersion: v1
kind: Pod
metadata:
  name: frontendpod
spec:
  containers:
  - name: frontend
    image: carlosquintanilha/frontendimage
    ports:
    - containerPort: 8501
    env:
    - name: API_URL
      value: "http://api:8000"
    - name: UPDATED
      value: "yes"


API_URL: http://api:8000
      UPDATED: yes